services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes: 
      - data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mentorship
      POSTGRES_USER: mentor
 
  backend:
    build: 
     context: .
     dockerfile: ./Dockerfile
    working_dir: /
    ports: 
      - "8080:5000"
    depends_on:
      - postgres
    environment:
      DB_NAME: mentorship
      DB_USER: mentor
      DB_PASS: secret

volumes:
  data:

